FORMAT: 1A
HOST: http://tubis.cz/api/v1/

# Tubis

Tubis API is the REST API project for managing events, users, documents, etc.

# Data Structures

## Auth (object)
+ username: "hrabalo" (string, required)
+ password: "123456" (string, required)

## Role (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ role: "ADMIN" (string, required)

## User (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ username: "hrabalo" (string, required)
+ forename: "Ondřej" (string, required)
+ surname: "Hrabal" (string, required)
+ role: "ADMIN" (string, required)
+ active: true (boolean, required)

## User Password (object)
+ password: "123456" (string, required)

## Report (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ automatic: true (boolean, required)
+ source: "KERBERUS" (string, required)
+ title: "Rozbitá žárovka" (string, required)
+ severity: "COMMONOCCURRENCE" (string, required)
+ priority: 1 (number, required)
+ description: Car stops in tunnel (string, required)
+ created: "2014-09-11T17:02:27.761+02:00" (string, required)
+ processed: "2014-09-11T17:02:27.761+02:00" (string, required)
+ author: {} (Author, optional)
+ type: {} (ReportType, optional)
+ parentType: {} (ReportParentType, required)
+ events: [] (array[SimpleEvent], optional)

## ReportUpdate (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ title: "Rozbitá žárovka" (string, required)
+ name: "Závažná porucha nebo havárie na technologickém zařízení: výpadek vzduchotechniky" (string, required)
+ description: Car stops in tunnel (string, required)
+ note: "nejde elektrika" (string, optional)
+ author: {} (Author, required)
+ source: "KERBERUS" (string, required)
+ state: "NEW" (string, required)
+ priority: 1 (number, required)
+ severity: "COMMONOCCURRENCE" (string, required)
+ location: "přesně uprostřed" (string, optional)
+ parentType: {} (ReportParentType, required)
+ type: {} (ReportType, optional)
+ created: "2014-09-11T17:02:27.761+02:00" (string, required)
+ events: [] (array[SimpleEvent], optional)
+ sourceName: "CCTV dohled" (string, required)
+ stateName: "Nové" (string, required)
+ severityName: "Krizová situace" (string, required)

## Reports (object)
+ reports: [] (array[Report], required)

## ReportSeverity (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ name: "Běžná událost" (string, required)

## ReportParentType (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ code: "010" (string, required)
+ name: "Pořár" (string, required)

## ReportType (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ code: "011" (string, required)
+ name: "Požár v tunelovém komplexu" (string, required)
+ priority: 99 (number, required)

## ReportSource (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ name: "SMS" (string, required)

## ReportState (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ state: "NEW" (string, required)

## SimpleEvent (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ title: "Požár v tunelu" (string, required)
+ state: "NEW" (string, required)

## Severity (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ name: "běžná událost BU" (string, required)

## EventType (object)
+ code: "010" (string, required)
+ name: "Zvýšení obsahu škodlivin v ovzduší nad kritický limit" (string, required)
+ priority: 99 (number, required)
+ title: "5.1" (string, required)

## Author (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ forename: "Jan" (string, required)
+ surname: "Dlaždička" (string, required)

## Owner (object)
+ locked: true (string, required) - This is set to false for person who locked the event/step/form.
+ forename: "Jan" (string, required)
+ surname: "Dlaždička" (string, required)
+ created: "2014-09-11T17:02:27.761+02:00" (string, required)

## Event (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ title: "Požár" (string, required)
+ created: "2014-09-11T17:02:27.761+02:00" (string, required)
+ closed: "2014-09-11T17:02:27.761+02:00" (string, required)
+ state: "NEW" (string, required)
+ characteristic: "" (string, optional)
+ dueToACondition: "" (string, optional)
+ descriptionRmd: "" (string, optional)
+ resultState: "" (string, required)
+ activityDescription: "" (string, required)
+ source: "KERBERUS" (string, required)
+ regime: {} (Regime, required)
+ form: {} (Form, required)
+ location: "Sektor C1" (string, optional)
+ type: {} (EventType, required)
+ severity: {} (Severity, required)
+ owner: {} (Owner, optional)
+ author: {} (Author, required)
+ notes: [] (array[EventNote], required)
+ reports: ["125f9669-af7a-4eeb-b7e5-7f1d7286e195", "e27164e8-f8cd-47df-a5af-1c121e9aa94a"] (array[string], required)
+ steps: {} (EventSteps, required)
+ contacts: [] (array[Contact], optional)
+ attachments: [] (array[Attachment], optional)

## EventNote
+ author: {} (Author, required)
+ created: "2014-09-11T17:02:27.761+02:00" (string, required)
+ text: "Poznámka" (string, required)

## EventLock  (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ title: "Požár" (string, required)
+ created: "2014-09-11T17:02:27.761+02:00" (string, required)
+ state: "NEW" (string, required)
+ source: "KERBERUS" (string, required)
+ location: "Sektor C1" (string, optional)
+ type: {} (EventType, required)
+ severity: {} (Severity, required)
+ owner: {} (Owner, required)
+ author: {} (Author, required)

## Regime (object)
+ code: "MR" (string, required)
+ name: "Mimořádný režim" (string, required)

## Contact (object)
+ organization: "PČR" (string, optional)
+ workplace: "odtahy" (string, optional)
+ position: "plk." (string, optional)
+ forename: "Petr" (string, optional)
+ surname: "Dostřel" (string, optional)
+ phone: "+420777888999" (string, optional)
+ mobile: "+420777888999" (string, optional)
+ email: "pmc1@praha.cz" (string, optional)
+ analogRdst: "159 Mhz" (string, optional)
+ pegas: "kanal 112" (string, optional)

## AttachmentData (object)
+ content: "data:image/png;base64,iVBORw0KGgoAAA..." (string, required)
+ contentType: "image/jpeg" (string, required)
+ filename: "Photo.jpg" (string, required)

## Attachment (object)
+ id: 1 (number, required)
+ link: "/cdn/file/A3..." (string, required)
+ name: "Photo.jpg"

## EventSteps (object)
+ technology: [] (array[EventStep], required)
+ traffic: [] (array[EventStep], required)
+ other: [] (array[EventStep], required)

## EventStep (object) 
+ id: "e27164e8-f8cd-47df-a5af-1c121e9aa94a" (string, required)
+ heading: "Permoník v šachtě" (string, required)
+ position: 1 (number, required)
+ slot: 1 (number, required)
+ remark: "Nepodařilo se dovolat" (string, optional)
+ owner: {} (Owner, optional)
+ description: "Zavolej na PČR" (string, optional)
+ closed: "2014-09-11T17:02:27.761+02:00" (string, required)
+ attachments: [] (array[Attachment], required)
+ contacts: [] (array[Contact], required)
+ documents: [] (array[Attachment], required)

## TemplateDocuments (object)
+ documents: [] (array[Attachment], required)

## Template (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ severity: {} (Severity, required)
+ type: "011" (string, required)
+ parentType: "010" (string, required)
+ title: "Požár" (string, required)
+ regime: {} (Regime, required)
+ form: {} (TemplateForm, required)
+ priority: 99 (number, required)
+ name: "Zvýšení obsahu škodlivin v ovzduší nad kritický limit" (string, required)
+ description: "" (string, optional)
+ characteristic: "" (string, optional)
+ dueToACondition: "" (string, optional)
+ descriptionRmd: "" (string, optional)

## TemplateForm (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ sysname: "form01" (string, required)
+ groups: [] (array[TemplateFormGroup], required)

## TemplateFormGroup (object)
+ label: "Zakladni" (string, required)
+ name: "baseGroup" (string, required)
+ controls: [] (array[TemplateFormControl], required)

## TemplateFormControl (object)
+ id: "e27164e8-f8cd-47df-a5af-1c121e9aa94a" (string, required)
+ order: 1 (number, required)
+ isreadonly: true (boolean, required)
+ definition: {} (TemplateControlDefinition, required)

## TemplateControlDefinition (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e19a" (string, required)
+ sysname: "currentTime" (string, required)
+ label: "Aktualni cas" (string, required)
+ validationregex: "" (string, optional)
+ type: {} (TemplateControlEnumType, required)
+ subtype: {} (TemplateControlEnumType, optional)
+ preferedhtmltag: "div" (string, required)
+ enumitems: [] (TemplateControlEnumType, optional)

## TemplateControlEnumType (object)
+ code: 1 (number, required)
+ label: "Aktualni cas" (string, required)

## EventFormLock (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ title: "Požár" (string, required)
+ created: "2014-09-11T17:02:27.761+02:00" (string, required)
+ state: "NEW" (string, required)
+ source: "KERBERUS" (string, required)
+ location: "Sektor C1" (string, optional)
+ type: {} (EventType, required)
+ severity: {} (Severity, required)
+ author: {} (Author, required)
+ form: [] (Form, required)

## EventStepLock (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ title: "Požár" (string, required)
+ created: "2014-09-11T17:02:27.761+02:00" (string, required)
+ state: "NEW" (string, required)
+ source: "KERBERUS" (string, required)
+ location: "Sektor C1" (string, optional)
+ type: {} (EventType, required)
+ severity: {} (Severity, required)
+ author: {} (Author, required)
+ steps: [] (array[StepLock], required)

## StepLock  (object)
+ id: "125f9669-af7a-4eeb-b7e5-7f1d7286e195" (string, required)
+ position: 1 (number, required)
+ slot: 1 (number, required)
+ remark: "Nepodařilo se dovolat" (string, optional)
+ owner: {} (Owner, required)
+ description: "Zavolej na PČR" (string, required)

## Events (object)
+ events: [] (array[Event], required)

## FileInfo (object)
+ key: "bf8f98b30d254efeae7ea5f3da0091af" (string, required)
+ contentType: "image/jpeg" (string, required)
+ fileName: "test,jpg" (string, required)
+ keyWords: "test" (string, optional)
+ created: "2015-11-05T18:44:00.0508545+01:00" (datetime, required)
+ changed: "2015-11-05T18:44:00.0508545+01:00" (datetime, required)

## FileData (object)
+ key: "bf8f98b30d254efeae7ea5f3da0091af" (string, required)
+ contentType: "image/jpeg" (string, required)
+ fileName: "test,jpg" (string, required)
+ keyWords: "test" (string, optional)
+ created: "2015-11-05T18:44:00.0508545+01:00" (datetime, required)
+ changed: "2015-11-05T18:44:00.0508545+01:00" (datetime, required)
+ content: "/9j/4AAQSkZJRgAB ... X/2Q==" (string, required)

## InsertFile (object)
+ contentType: "image/jpeg" (string, required)
+ fileName: "test,jpg" (string, required)
+ keyWords: "test" (string, optional)

## UpdateFile (object)
+ key: "bf8f98b30d254efeae7ea5f3da0091af" (string, required)
+ contentType: "image/jpeg" (string, required)
+ fileName: "test,jpg" (string, required)
+ keyWords: "test" (string, optional)

## Form (object)
+ owner: {} (Owner, optional)
+ blueprint: {} (FormBlueprint, required)

## FormBlueprint (object)
+ groups: [] (array[FormGroup], required)

## FormGroupData (object)
+ inputs: [] (array[FormInput], required)

## FormGroup (object)
+ label: "test,jpg" (string, required)
+ name: "confirmed" (string, required)
+ inputs: [] (array[FormInput], required)
+ owner: {} (Owner, optional)

## FormGroupValue (object)
+ name: "confirmed" (string, required)
+ inputs: [] (array[FormValue], required)

## FormInput (object)
+ order: 1 (number, optional)
+ label: "test,jpg" (string, required)
+ name: "confirmed" (string, required)
+ value: "1" (string, optional)
+ type: "checkbox" (string, required)
+ options: [] (array[InputOptions], optional)

##FormValue (object)
+ name: "confirmed" (string, required)
+ value: "1" (string, required)

## InputOptions (object)
+ value: "1" (string, required)
+ label: "Number" (string, required)

# Group Authentication
The authentication resources can be used for **log in** and **log out** the user to the Tubis application.

## /tunnels/{tunnelId}/authentication

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.

### POST

**Returns the private API token key for the user with its validity**


+ Request
    + Attributes (Auth)
    
    + Header
    
            Content-Type: application/json

    + Body
    
            {
                "username" : "username",
                "password" : "123456"
            }

+ Response 200 (application/json)

    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
    
    
    + Body

            {
                "id": "125f9669-af7a-4eeb-b7e5-7f1d7286e195",
                "token": "fc7ef14ba27e29c89ec640cec3b91fb374db9b5abaa5e4699680c8c561bd9f5a",
                "email": "novakj@tubis.cz",
                "username": "novakj",
                "forename": "Jan",
                "surname": "Novák",
                "validity": "2015-09-09T21:58:31+02:00",
                "role": "ADMIN"
            }

+ Response 400
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### DELETE
**Logs out the user by the Api-Key, if the response is successful.**


+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 204

    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### PUT

**Reconnects the user by the Api-Key, if the response is successful.**


+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
            
    + Body

            {
                "validity": "2015-09-09T21:58:31+02:00"
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503


# Group Role
The role resources can be used for managing user roles.

## /tunnels/{tunnelId}/roles

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.

### GET
**List of roles.**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

    + Attributes (Role)
    
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    
            {
                "roles": [
                    {
                        "id": "ce1ffea6-b59d-4135-8ffe-6f77bfc14028",
                        "role": "ADMIN"
                    },
                    {
                        "id": "b63b6226-0978-4155-8249-1ca396f6c7e7",
                        "role": "OPERATOR"
                    },
                    {
                        "id": "bc93fdec-7b57-4c3b-a232-5cd112308b58",
                        "role": "POLICE"
                    }
                ]
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

# Group User
The user resources can be used for managing users.

## /tunnels/{tunnelId}/users

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.

### GET
**List of users.**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

    + Attributes (User)
    
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    
            {
                "users": [
                    {
                        "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
                        "email": "hrabalo@quanti.cz",
                        "username": "hrabadlo",
                        "forename": "Ondřej",
                        "surname": "Schrabal",
                        "role": "ADMIN",
                        "active": false
                    },
                    {
                        "id": "125f9669-af7a-4eeb-b7e5-7f1d7286e195",
                        "email": "blazekv@quanti.cz",
                        "username": "blazekv",
                        "forename": "Vlastislav",
                        "surname": "Blažek",
                        "role": "OPERATOR",
                        "active": true
                    }
                ]
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### POST
**Create user**

+ Request
    + Attributes (User)
    
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>
    
    + Body 
    
            {
                "email": "blazekv@quanti.cz",
                "username": "blazekv",
                "forename": "Vlastislav",
                "surname": "Blažek",
                "role": "OPERATOR",
                "password": "xxxxx",
                "active": true
            }
            
+ Response 201 (application/json)
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
            Location: /tunnels/{tunnelId}/users/{id}
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/users/{id}

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + id (required, string, `b63b6226-0978-4155-8249-1ca396f6c7e7`) ... String `id`which can identify user.

### GET
**Get user**

+ Request

    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

    + Attributes (User)
    
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
            
            
    + Body
    
            {
                "id": "125f9669-af7a-4eeb-b7e5-7f1d7286e195",
                "email": "blazekv@quanti.cz",
                "username": "hrabalo",
                "forename": "Ondřej",
                "surname": "Hrabal",
                "role": "ADMIN",
                "active": true
            }

+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### PUT
**Update user**

+ Request
    + Attributes (User)

    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

    + Body
    
            {
                "email": "blazekv@quanti.cz",
                "username": "hrabalo",
                "forename": "Ondřej",
                "surname": "Hrabal",
                "role": "ADMIN",
                "active": true
            }

+ Response 204

    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00

+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### DELETE
**Delete user**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 204

    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
            
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/users/{id}/events

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + id (required, string, `b63b6226-0978-4155-8249-1ca396f6c7e7`) ... String `id`which can identify user.

### GET
**List of user events**

+ Request

    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

    + Attributes (Event)

    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
            
            
    + Body
    
            {
              "events": [
                {
                  "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
                  "created": "2014-09-11T17:02:27.761+02:00",
                  "closed":  "2014-09-11T17:02:27.761+02:00",
                  "type": {
                    "code": "011",
                    "name": "Zvýšení obsahu škodlivin v ovzduší nad kritický limit",
                    "priority": 6,
                    "title": "6.1"
                  },
                  "severity": {
                    "id": "1",
                    "name": "běžná událost BU"
                  },
                  "author": {
                    "id": 1,
                    "forename": "Jan",
                    "surname": "Dlaždička"
                  },
                  "reports": [1,3,4]
                }
              ]
            }

+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/users/{id}/password

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + id (required, string, `b63b6226-0978-4155-8249-1ca396f6c7e7`) ... String `id`which can identify user.

### PUT
**Change user password.**

+ Request
    + Attributes (User Password)

    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

    + Body
    
            {
                "password": "123456"
            }

+ Response 204

    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
            
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

# Group Templates
The template resources can be used for managing events templates.

## /tunnels/{tunnelId}/templates

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.

### GET

**List of event templates**


+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>
            
+ Response 200 (application/json)
    
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    
            {
              "templates": [
                {
                    "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
                    "severity": {
                        "id": "1",
                        "name": "běžná událost BU"
                    },
                    "type": "011",
                    "parentType": "010",
                    "title": "Prasklé potrubí",
                    "regime": {
                        "code": "MR",
                        "name": "Mimořádný režim"
                    },
                    "priority": 6,
                    "name": "ts1",
                    "description": "se to pokazilo",
                    "characteristic": "nullovatelné - charakteristika udalosti",
                    "duetoacondition": "nullovatelné - následek stavu",
                    "descriptionrmd": "nullovatelné - popis cinnosti ŘS",
                }
              ]
            }

+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/templates/{templateId}/form

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + templateId (required, string, `g2h9664e8-f8cd-47df-a5af-1cd821e9aaa`) ... String `templateId`which can identify template.

### GET

**Form definition object. Returns empty object in case the template doesn't have form yet**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>
            
+ Response 200 (application/json)
    
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    
            {
                "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94b",
                "sysname": "form05",
                "groups": [
                    {
                        "label": "Zakladni",
                        "name": "baseGroup",
                        "controls": [
                            {
                                "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94c",
                                "order": 1,
                                "isreadonly": false,
                                "definition": {
                                    "id": "125f9669-af7a-4eeb-b7e5-7f1d7286e19a",
                                    "sysname": "currentTime",
                                    "label": "Aktualni cas",
                                    "validationregex": "(.*)",
                                    "type": {
                                        "code": 1,
                                        "label": "string"
                                    } 
                                    "subtype": {
                                        "code": 2,
                                        "label": "text"
                                    } 
                                    "preferedhtmltag": "div",
                                    "enumitems": [
                                        {
                                            "code": 0,
                                            "label": "prvni"
                                        },
                                        {
                                            "code": 1,
                                            "label": "druha"
                                        }
                                    ]
                                }
                            },
                            {
                                "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94d",
                                "order": 2,
                                "isreadonly": false,
                                "definition": {
                                    "id": "125f9669-af7a-4eeb-b7e5-7f1d7286e19a",
                                    "sysname": "carsCount",
                                    "label": "Pocet automobilu",
                                    "type": {
                                        "code": 2,
                                        "label": "integer"
                                    } 
                                    "preferedhtmltag": "input"
                                }
                            }
                        ]
                    },
                    {
                        "label": "rozsireny",
                        "name": "extGroup",
                        "controls": [
                            {
                                "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94c",
                                "order": 1,
                                "isreadonly": false,
                                "definition": {
                                    "id": "125f9669-af7a-4eeb-b7e5-7f1d7286e19a",
                                    "sysname": "currentTime",
                                    "label": "Aktualni cas",
                                    "validationregex": "(.*)",
                                    "type": {
                                        "code": 1,
                                        "label": "string"
                                    } 
                                    "subtype": {
                                        "code": 2,
                                        "label": "text"
                                    } 
                                    "preferedhtmltag": "div",
                                    "enumitems": [
                                        {
                                            "code": 0,
                                            "label": "prvni"
                                        },
                                        {
                                            "code": 1,
                                            "label": "druha"
                                        }
                                    ]
                                }
                            },
                            {
                                "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94d",
                                "order": 2,
                                "isreadonly": false,
                                "definition": {
                                    "id": "125f9669-af7a-4eeb-b7e5-7f1d7286e19a",
                                    "sysname": "carsCount",
                                    "label": "Pocet automobilu",
                                    "type": {
                                        "code": 2,
                                        "label": "integer"
                                    } 
                                    "preferedhtmltag": "input"
                                }
                            }
                        ]
                    }
                ]
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/templates/{templateId}/steps 

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + templateId (required, string, `g2h9664e8-f8cd-47df-a5af-1cd821e9aaa`) ... String `templateId`which can identify template.

### GET

**List of template steps**


+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>
            
+ Response 200 (application/json)
    
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    
            {
              "steps": [
                {}
              ]
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### POST

**Create template step**


+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>
            
    + Body 
    
            {
                "position": 1,
                "heading": "Permoník v šachtě",
                "slot": 2,
                "remark": "Nepodařilo se dovolat",
                "description": "Zavolej na PČR"
            }
            
+ Response 201 (application/json)
    
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    
            {
                "id": 1,
                "position": 1,
                "heading": "Permoník v šachtě",
                "slot": 2,
                "remark": "Nepodařilo se dovolat",
                "description": "Zavolej na PČR"
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/templates/{templateId}/steps/{stepId}

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + templateId (required, string, `g2h9664e8-f8cd-47df-a5af-1cd821e9aaa`) ... String `templateId`which can identify template.
    + stepId (required, string, `g2h6564e8-f9cd-44df-25af-1cd821e9aaa`) ... String `stepId`which can identify template step.


### PUT

**Update template step**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>
            
    + Body 
    
            {
                "id": 1,
                "position": 1,
                "heading": "Permoník v šachtě",
                "slot": 2,
                "remark": "Nepodařilo se dovolat",
                "description": "Zavolej na PČR"
            }
            
+ Response 204
    
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### DELETE

**Delete template step**


+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>
            
+ Response 204
    
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
    
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/templates/{templateId}/documents

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + templateId (required, string, `g2h9664e8-f8cd-47df-a5af-1cd821e9aaa`) ... String `templateId`which can identify template.

### GET

**List of template documents**


+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>
            
+ Response 200 (application/json)

    + Attributes(TemplateDocuments)
    
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    
            {
              "documents": [
                {
                  "id": "fb89365084b943a98c7aa2081d1fadcf",
                  "link": "/cdn/file/fb893650-84b9-43a9-8c7a-a2081d1fadcf",
                  "name": "1.jpg"
                }
              ]
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### POST

**Create step document**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

    + Body 
    
            {
                "content": "data:application/pdf;base64,JVBERi0x....LjQKJ0YK="
                "contentType": "application/pdf"
                "filename": "informace.pdf"
            }

+ Response 204 
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/template/{templateId}/documents/{fileId}

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + templateId (required, string, `g2h9664e8-f8cd-47df-a5af-1cd821e9aaa`) ... String `templateId`which can identify template.
    + fileId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `fileId`which can identify file.
    
### DELETE

**Delete step document**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 204 
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/templates/{templateId}/contacts

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + templateId (required, string, `g2h9664e8-f8cd-47df-a5af-1cd821e9aaa`) ... String `templateId`which can identify template.

### GET

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>
            
+ Response 200 (application/json)

    + Attributes(TemplateDocuments)
    
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    
            {
              "contacts": [
                {
                    "organization": "PČR",
                    "workplace": "Oddělení dopravy",
                    "position": "plk.",
                    "forename": "Ondřej",
                    "surname": "Schrabal",
                    "phone": "987654321",
                    "mobile": "123456789",
                    "email": "hrabalo@quanti.cz",
                    "analogRdst": "110Mhz",
                    "pegas": ""
                },
                {
                    "organization": "PČR",
                    "workplace": "Oddělení dopravy",
                    "position": "plk.",
                    "forename": "Ondřej",
                    "surname": "Schrabal",
                    "phone": "987654321",
                    "mobile": "123456789",
                    "email": "hrabalo@quanti.cz",
                    "analogRdst": "110Mhz",
                    "pegas": ""
                }
              ]
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### POST
-----------
**Create template contact.**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

    + Body 
    
            {
                "organization": "PČR",
                "workplace": "Oddělení dopravy",
                "position": "plk.",
                "forename": "Ondřej",
                "surname": "Schrabal",
                "phone": "987654321",
                "mobile": "123456789",
                "email": "hrabalo@quanti.cz",
                "analogRdst": "110Mhz",
                "pegas": ""
            }

+ Response 201 
    + Header
    
            Location: /contacts/1
            X-Time: 2014-09-11T17:02:27.761+02:00
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/template/{templateId}/contacts/{contactId}

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + templateId (required, string, `g2h9664e8-f8cd-47df-a5af-1cd821e9aaa`) ... String `templateId`which can identify template.
    + contactId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `contactId`which can identify contact.

### PUT
-----------
**Update template contact.**

+ Request
    + Attributes (Contact)

    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

    + Body
    
            {
                "organization": "PČR",
                "workplace": "Oddělení dopravy",
                "position": "plk.",
                "forename": "Ondřej",
                "surname": "Schrabal",
                "phone": "987654321",
                "mobile": "123456789",
                "email": "hrabalo@quanti.cz",
                "analogRdst": "110Mhz",
                "pegas": ""
            }

+ Response 204

    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00

+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### DELETE
-----------
**Deletes template contact.**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 204

    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
            
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

# Group Event
The event resources can be used for managing events.

## /tunnels/{tunnelId}/events

### GET
**List of events**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

    + Attributes (Event)
    
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    
            {
              "events": [
                {
                  "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
                  "created": "2014-09-11T17:02:27.761+02:00",
                  "closed":  "2014-09-11T17:02:27.761+02:00",
                  "type": {
                    "code": "011",
                    "name": "Zvýšení obsahu škodlivin v ovzduší nad kritický limit",
                    "priority": 6,
                    "title": "6.1"
                  },
                  "severity": {
                    "id": "1",
                    "name": "běžná událost BU"
                  },
                  "author": {
                    "id": 1,
                    "forename": "Jan",
                    "surname": "Dlaždička"
                  },
                  "reports": [1,3,4]
                }
              ]
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/events?locked=true

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.

### Get locked events [GET]

**List of locked events**


+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json) 
    + Attributes (EventLock)

    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
    + Body
    
            {
                "events": [
                    {
                      "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
                      "title": "Prasklé potrubí",
                      "location": "Potrubí",
                      "characteristic": "Charakteristika události",
                      "activityDescription": "Popis činnosti",
                      "stateResult": "Následek stavu",
                      "source": "KERBERUS",
                      "created": "2014-09-11T17:02:27.761+02:00",
                      "type": {
                        "code": "011",
                        "name": "Zvýšení obsahu škodlivin v ovzduší nad kritický limit",
                        "priority": 6,
                        "title": "6.1"
                      },
                      "severity": {
                        "id": "1",
                        "name": "běžná událost BU"
                      },
                      "author": {
                        "id": 1,
                        "forename": "Jan",
                        "surname": "Dlaždička"
                      },
                      "owner": {
                        "id": 1,
                        "locked": true,
                        "forename": "Jan",
                        "surname": "Dlaždička",
                        "created": "2014-09-11T17:02:27.761+02:00"
                       }
                    }
                ]
            }

+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/events/{id}

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + id (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `id`which can identify event.

### GET
**Get event**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

    + Attributes (Event)
    
    + Header

             X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    

            {
              "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
              "title": "Prasklé potrubí",
              "location": "Potrubí",
              "characteristic": "Charakteristika události",
              "activityDescription": "Popis činnosti",
              "stateResult": "Následek stavu",
              "source": "KERBERUS",
              "created": "2014-09-11T17:02:27.761+02:00",
              "closed":  "2014-09-11T17:02:27.761+02:00",
              "type": {
                "code": "011",
                "name": "Zvýšení obsahu škodlivin v ovzduší nad kritický limit",
                "priority": 6,
                "title": "5.2"
              },
              "regime": {
                "code": "MR",
                "name": "Mimořádný režim"
              },
              "severity": {
                "id": "1",
                "name": "běžná událost BU"
              },
              "author": {
                "id": 1,
                "forename": "Jan",
                "surname": "Dlaždička"
              },
              "form": {
                "owner": {
                    "id": 3,
                    "locked": true,
                    "forename": "Pepa",
                    "surname": "Z depa",
                    "created": "2015-10-12T18:02:24.047+0:00"
                },
                "blueprint": {
                  "groups": [
                    {
                      "label": "Průběh řešení události",
                      "name": "ts1",
                      "owner": {
                        "locked": false,
                        "forename": "Petr",
                        "surname": "Zelený",
                        "created": "2014-09-11T17:02:27.761+02:00"
                      }
                      "inputs": [
                        {
                          "order": 1,
                          "label": "Vytvořeno",
                          "name": "created",
                          "type": "text",
                          "placeholder": "tohle je text",
                          "value": "Hodnota pole"
                        },
                        {
                          "order": 2,
                          "label": "Uzavřeno",
                          "name": "closed",
                          "type": "radio"
                        },
                        {
                          "order": 4,
                          "label": "Komentář",
                          "name": "comment",
                          "type": "datetime",
                          "value": "2015-10-12T18:02:24.047+01:00"
                        },
                        {
                          "order": 5,
                          "label": "Výběr",
                          "name": "selection",
                          "type": "select",
                          "value": "2",
                          "options": [
                            {
                              "value": 1,
                              "label": "test1"
                            },
                            {
                              "value": 2,
                              "label": "test2"
                            }
                          ]
                        },
                        {
                          "order": 3,
                          "label": "Výběr 2",
                          "name": "asdd",
                          "type": "radiolist",
                          "options": [
                            {
                              "value": 1,
                              "label": "test1"
                            },
                            {
                              "value": 2,
                              "label": "test2"
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "label": "Průběh řešení události 2",
                      "name": "ts2",
                      "inputs": [
                        {
                          "label": "Vytvořeno",
                          "name": "created",
                          "type": "text",
                          "placeholder": "tohle je text"
                        },
                        {
                          "label": "Uzavřeno",
                          "name": "closed",
                          "type": "radio"
                        },
                        {
                          "label": "Komentář",
                          "name": "comment",
                          "type": "datetime"
                        },
                        {
                          "label": "Výběr",
                          "name": "selection",
                          "type": "select",
                          "options": [
                            {
                              "value": 1,
                              "label": "test1"
                            },
                            {
                              "value": 2,
                              "label": "test2"
                            }
                          ]
                        },
                        {
                          "label": "Výběr 2",
                          "name": "asdd",
                          "type": "radiolist",
                          "options": [
                            {
                              "value": 1,
                              "label": "test1"
                            },
                            {
                              "value": 2,
                              "label": "test2"
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              }
              "steps": {
                "technology" : [
                  {
                    "id": 1,
                    "position": 1,
                    "remark": "Nepodařilo se dovolat",
                    "description": "Zavolej na PČR",
                    "closed": "2014-09-11T17:02:27.761+02:00",
                    "attachments": [],
                    "organizationsContacts": [
                        {
                          "name": "PČR",
                          "contacts": [
                            {
                              "workplace": "Odtahy",
                              "position": "odtahovač",
                              "firstname": "",
                              "surname": "",
                              "phone": "+42074747747",
                              "mobile": "+42074747747",
                              "email": "info@sshmp.cz",
                              "analogRadioStation": "169 MHz",
                              "pegas": "kanál 112"
                            } ,
                            {
                              "workplace": "Kriminalistika",
                              "position": "detektiv",
                              "firstname": "Jan",
                              "surname": "Drsný",
                              "phone": "+42074747747",
                              "mobile": "+42074747747",
                              "email": "info@sshmp.cz"
                            }  
                          ]
                        },
                        {
                          "name": "IZS",
                          "contacts": [
                            {
                              "workplace": "Hasiči",
                              "position": "hasič",
                              "firstname": "Petr",
                              "surname": "Vodný",
                              "phone": "+42074747747",
                              "mobile": "+42074747747",
                              "email": "info@sshmp.cz",
                              "analogRadioStation": "169 MHz",
                              "pegas": "kanál 112"
                            }
                          ]
                        } 
                    ],
                  }
                ],
                "traffic" : [
                  {
                    "id": 1,
                    "position": 1,
                    "remark": "Nepodařilo se dovolat",
                    "description": "Zavolej na PČR",
                    "closed": "2014-09-11T17:02:27.761+02:00",
                    "attachments": []
                  }
                ],
                "other" : [
                  
                ]
              },
              "reports": [1,3,4]
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### PUT
**Update event**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

    + Body 
    
            {
                  "location": "Potrubí",
                  "source": "CCTV",
                  "title": "Prasklé potrubí"
            }

+ Response 204
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503


## /tunnels/{tunnelId}/events/{id}/notes

### POST
**Create event note**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>
    
    + Body 
    
            {
                "text": "Testovací poznámka"
            }

+ Response 201
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/events/{id}/started

### PUT
**It will change started timestamp only for the first time. It will set started to now.**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 204
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/events/{id}/lock

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + id (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `id`which can identify event.

### PUT
**Create or refresh event lock**


+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 204 
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### DELETE
**Delete event lock**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 204 
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503


## /tunnels/{tunnelId}/events/{id}/form/{formGroup}/data

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + id (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `id`which can identify event.
    + formGroup (required, string, `default`) ... String `default` which can form group.

### PUT
**Update form group data**


+ Request

    + Attributes (FormGroupData)

    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

    + Body
    
            {
                "inputs": [
                    {
                        "name": "created",
                        "value": "2015-10-12T18:02:24.047+01:00"
                    },
                    {
                        "name": "text",
                        "value": "Vuz prijel pozde"
                    }
                ]
            }

+ Response 204 
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/events/{id}/form/{formGroup}/lock

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + id (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `id`which can identify event.
    + formGroup (required, string, `default`) ... String `default` which can form group.

### PUT
**Create or refresh event form group lock**


+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 204 
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### DELETE
**Delete event form group lock**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 204 
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503


## /tunnels/{tunnelId}/events/{eventId}/attachments

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + eventId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `eventId`which can identify event.
    
### POST
**Create event attachment**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

    + Body 
    
            {
                "content": "data:application/pdf;base64,JVBERi0x....LjQKJ0YK="
                "contentType": "application/pdf"
                "filename": "informace.pdf"
            }

+ Response 204 
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/events/{eventId}/attachments/{fileId}

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + eventId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `eventId`which can identify event.
    + fileId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `fileId`which can identify file.
    
### DELETE
**Delete event attachment**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 204 
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503


## /tunnels/{tunnelId}/events/{eventId}/steps/{stepId}

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + eventId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `eventId`which can identify event.
    + stepId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `stepId`which can identify step event.

### GET
**Get event step**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

    + Attributes (Event)
    
    + Header

             X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    

            {
                "id": 1,
                "position": 1,
                "slot": 1,
                "heading": "Volání o pomoc",
                "remark": "Nepodařilo se dovolat",
                "description": "Zavolej na PČR",
                "closed": "2014-09-11T17:02:27.761+02:00",
                "attachments": []
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### PUT
**Update event step**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

    + Attributes (Event)
    
    + Header

             X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    

            {
                "remark": "Nepodařilo se dovolat",
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/events/{eventId}/steps/{stepId}/closed

**This resource will also setup started on the step, if is not setup. It will update closed attribute everytime**

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + eventId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `eventId`which can identify event.
    + stepId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `stepId`which can identify step event.

### PUT
**Close step**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 204
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/events/{eventId}/steps/{stepId}/lock


+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + eventId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `eventId`which can identify event.
    + stepId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `stepId`which can identify step event.

### PUT
**Create or refresh event step lock**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 204
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503



### DELETE
**Delete event step lock**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 204
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503


## /tunnels/{tunnelId}/events/{eventId}/steps/{stepId}/attachments

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + eventId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `eventId`which can identify event.
    + stepId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `stepId`which can identify step event.

### POST
**Upload event step attachment**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

    + Attributes (AttachmentData)
    
    + Header

             X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    

            {
                "content": "data:application/pdf;base64,JVBERi0x....LjQKJ0YK="
                "contentType": "application/pdf"
                "filename": "informace.pdf"
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/events/{eventId}/steps/{stepId}/attachments/{fileId}

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + eventId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `eventId`which can identify event.
    + stepId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `stepId`which can identify step event.
    + fileId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `fileId`which can identify file.

### DELETE
-----------
**Delete event step attachment**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 204
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503


# Group Content Delivery Network
The CDN resource should be used to store and manage all kind of document related to the tunnel application.

## /cdn/allowedcContentTypes
List of all supported content types

### GET
**Returns dictionary with file extensions as keys and MIME types as values**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

        {
            ".evy": "application/envoy",
            ".fif": "application/fractals",
            ".spl": "application/futuresplash",
            ".hta": "application/hta",
            ".acx": "application/internet-property-stream",
            ".hqx": "application/mac-binhex40",
            ".doc": "application/msword",
            ".dot": "application/msword",
            ".bin": "application/octet-stream"
            ...
        }

## /cdn/fileInfos
Offers metadata to all file in cdn

### GET
**Returns all files meta data**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

        [{
            "key": "a2edfbad2c35479daf079ed508b0576f",
            "contentType": "image/jpeg",
            "fileName": "prostenazev.jpg",
            "keyWords": "manual",
            "created": "2015-11-06T12:33:58.0342335+01:00",
            "changed": "2015-11-06T12:33:58.0342335+01:00"
        }, {
            "key": "1f85be86c15b44ffb3c3d210d4143be3",
            "contentType": "image/jpeg",
            "fileName": "obrazek.jpg",
            "keyWords": "kniha",
            "created": "2015-11-05T19:27:28.6821174+01:00",
            "changed": "2015-11-05T19:27:28.6821174+01:00"
        }]

## /cdn/fileInfo/{key}
Offers metadata about one file

### GET
**Returns file meta data**

+ Parameters
    + key (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `key`which can identify file.

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

        {
            "key": "bf8f98b30d254efeae7ea5f3da0091af",
            "contentType": "image/jpeg",
            "fileName": "test,jpg",
            "keyWords": "test",
            "created": "2015-11-05T18:44:00.0508545+01:00",
            "changed": "2015-11-05T18:44:00.0508545+01:00"
        }

## /cdn/file/{key}
File management

### GET
**Returns stream with file content**

+ Parameters
    + key (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `key`which can identify file.

+ Request

    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200

        [12,45,..,56]
        
### POST
**Inserts new file into cdn and returns it's key. Content is base64 encoded, "data:..." is neither needed, neither required**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

    + Body

            {
                "contentType": "image/jpeg",
                "fileName": "prostenazev.jpg",
                "keyWords": "manual",
                "content": "data:image/png;base64,iVBORw0KGgoAAA..."
            }

+ Response 200 (application/json)

        "a2edfbad2c35479daf079ed508b0576f"
        
### PUT
**Updates file on CDN - key required. Content is base64 encoded, "data:..." is neither needed, neither required**

+ Parameters
    + key (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `key`which can identify file.

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

    + Body

            {
                "contentType": "image/jpeg",
                "fileName": "prostenazev.jpg",
                "keyWords": "manual",
                "content": "data:image/png;base64,iVBORw0KGgoAAA...",
            }

+ Response 200 (application/json)

        "true"

### DELETE
**Deletes file on CDN.**

+ Parameters
    + key (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `key`which can identify file.


+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

        "true"

## /cdn/search
Tries to find text in cdn metadata

### GET
------------
**Returns file meta data array (FileInfo). Or empty array in case of no result**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

    + Body

            {
                "onlyKeywords": "false",
                "searchFor": "jpg"
            }

+ Response 200 (application/json)

        [{
            "key": "a2edfbad2c35479daf079ed508b0576f",
            "contentType": "image/jpeg",
            "fileName": "prostenazev.jpg",
            "keyWords": "manual",
            "created": "2015-11-06T12:33:58.0342335+01:00",
            "changed": "2015-11-06T12:33:58.0342335+01:00"
        }, {
            "key": "bf8f98b30d254efeae7ea5f3da0091af",
            "contentType": "image/jpeg",
            "fileName": "test,jpg",
            "keyWords": "manual",
            "created": "2015-11-05T18:44:00.0508545+01:00",
            "changed": "2015-11-05T18:44:00.0508545+01:00"
        }]

# Group Schedulers 
The scheduler resources can be used for managing automatic schedule events.

## /tunnels/{tunnelId}/schedulers

# Group Reports 
The report resources can be used for managing reports.

## /tunnels/{tunnelId}/reports/{?states}

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + states (optional, string, `new`) .. String state which can filter reports.

### GET
**List of reports**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

    + Attributes (Reports)
    
    + Body 
    
            {
              "reports": [
                {
                  "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
                  "type": {
                    "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
                    "code": "021",              
                    "name": "Kočička v šachtě"
                  },
                  "automatic": false,
                  "note": "Kočička v šachtě",
                  "description": "V šachte se vyskytla kočicka. Vydává dešsivé zvuky. Pravděpodobně v sekci C1",
                  "author": {
                    "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
                    "forename": "Jan",
                    "surname": "Tunelář"
                  },
                  "source": "PHONE",
                  "severity": "COMMONOCCURRENCE",
                  "state": "NEW",
                  "priority": 1,
                  "created": "2014-10-20T17:11:27.761+02:00",
                  "processed": "2015-10-20T17:11:27.761+02:00",
                  "events": [
                    {
                        "id": 1,
                        "title": "Lov koček",
                        "state": "NEW"
                    },
                    {
                        "id": 2,
                        "title": "Neoprávněné vniknutí",
                        "state": "CLOSED"
                    }
                  ]
                },
                {
                  "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
                  "type": {
                    "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
                    "code": "021",              
                    "name": "Kočička v šachtě"
                  },
                  "automatic": false,
                  "note": "Kočička v šachtě",
                  "description": "V šachte se vyskytla kočicka. Vydává dešsivé zvuky. Pravděpodobně v sekci C1",
                  "author": {
                    "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
                    "forename": "Jan",
                    "surname": "Tunelář"
                  },
                  "source": "PHONE",
                  "severity": "COMMONOCCURRENCE",
                  "state": "NEW",
                  "priority": 1,
                  "created": "2014-10-20T17:11:27.761+02:00",
                  "processed": "2015-10-20T17:11:27.761+02:00",
                  "events": [
                    {
                        "id": 1,
                        "title": "Lov koček",
                        "state": "NEW"
                    },
                    {
                        "id": 2,
                        "title": "Neoprávněné vniknutí",
                        "state": "CLOSED"
                    }
                  ]
                }
              ]
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### POST
**Creates report**

+ Request
    + Attributes (Report)
    
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>
    
    + Body 
    
            {
              "type": "021",
              "note": "Kočička v šachtě",
              "description":  "V šachte se vyskytla kočicka. Vydává dešsivé zvuky. Pravděpodobně v sekci C1",
              "source": "PHONE",
              "state": "DONE",
              "priority": 1,
              "created": "2014-10-20T17:11:27.761+02:00"
            }
            
+ Response 201 (application/json)
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
            Location: /tunnels/{tunnelId}/reports/{id}
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/reports/{id}

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + id (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `id`which can identify report.

### GET
**Get report**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

    + Attributes (Reports)
    
    + Body 
    

            {
              "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
              "type": {
                "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
                "code": "021",              
                "name": "Kočička v šachtě"
              },
              "note": "Kočička v šachtě",
              "description": "V šachte se vyskytla kočicka. Vydává dešsivé zvuky. Pravděpodobně v sekci C1",
              "author": {
                "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
                "forename": "Jan",
                "surname": "Tunelář"
              },
              "source": "PHONE",
              "severity": "COMMONOCCURRENCE",
              "state": "NEW",
              "priority": 1,
              "created": "2014-10-20T17:11:27.761+02:00",
              "processed": "2015-10-20T17:11:27.761+02:00",
              "events": [
                {
                    "id": 1,
                    "title": "Lov koček",
                    "state": "NEW"
                },
                {
                    "id": 2,
                    "title": "Neoprávněné vniknutí",
                    "state": "CLOSED"
                }
              ]
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### PUT
**Update report**
+ Request
    + Attributes (ReportUpdate)
    
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>
    
    + Body 


            {
                "id": "458f3f110cde4b1fac3d9af930648521",
                "automatic": false,
                "title": "11.2",
                "name": "Závažná porucha nebo havárie na technologickém zařízení: výpadek vzduchotechniky ",
                "description": "",
                "note": "nejde elektrika",
                "author": {
                    "id": "b5d8b42a3f654521ace41f3cfa8d1274",
                    "forename": "Kerberus",
                    "surname": "Automatic"
                },
                "source": "CCTVSURVEILLANCE",
                "state": "DONE",
                "priority": 15,
                "severity": "CRISISSITUATION",
                "location": "",
                "parentType": {
                    "id": "31187b4ba4604193a004b8ff500c61e5",
                    "code": "110",
                    "name": "Závažná porucha nebo havárie na technologickém zařízení:"
                },
                "type": {
                    "id": "dcac87ed8b1f43e28e4c76dc25f6ed3e",
                    "code": "112",
                    "name": "Závažná porucha nebo havárie na technologickém zařízení: výpadek vzduchotechniky "
                },
                "created": "2016-01-04T11:12:27.4381530+01:00",
                "events": [],
                "sourceName": "CCTV dohled",
                "stateName": "Nové",
                "severityName": "Krizová situace"
            }
            
+ Response 201 (application/json)
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
            Location: /contacts/{id}

## /tunnels/{tunnelId}/reports/{id}/events/{eventId}

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + id (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `id`which can identify report.
    + eventId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `eventId`which can identify event.

### PUT
**Create event from report**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 204
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/reports/severities

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.

### GET
**List of report severities**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

    + Attributes (ReportSeverity)
    
    + Header

             X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    

            {
                "severities": [
                      {
                        "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
                        "severity": "COMMONOCCURRENCE"
                      },
                      {
                        "id": "b63b6226-0978-4155-8249-1ca396f6c7e7",
                        "severity": "CRISISSITUATION"
                      }
                ]
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/reports/parent-types

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.

### GET
**List of report parent types**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

    + Attributes (ReportParentType)
    
    + Header

             X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    

            {
                "parentTypes": [
                      {
                        "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
                        "code": "010",
                        "name": "Požár v tunelu"
                      },
                      {
                        "id": "b63b6226-0978-4155-8249-1ca396f6c7e7",
                        "code": "020",
                        "name": "Jiné nebezpečí"
                      }
                ]
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/reports/parent-types/{id}/types

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.
    + id (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `id`which can identify report parent type.

### GET
**List of report types by parent type id.**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

    + Attributes (ReportType)
    
    + Header

             X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    

            {
                "types": [
                      {
                        "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
                        "code": "011",
                        "name": "Požár v dopravním prostoru",
                        "priority": 5
                      },
                      {
                        "id": "b63b6226-0978-4155-8249-1ca396f6c7e7",
                        "code": "012",
                        "name": "Požár v technologickém prostoru",
                        "priority": 1
                      }
                ]
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/reports/sources

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.

### GET
**List of report sources**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

    + Attributes (ReportSource)
    
    + Header

             X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    

            {
                "sources": [
                      {
                        "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
                        "source": "SMS"
                      },
                      {
                        "id": "b63b6226-0978-4155-8249-1ca396f6c7e7",
                        "source": "Email"
                      },
                      {
                        "id": "b63b6226-0978-4155-8249-1ca396f6c7e7",
                        "source": "CCTV dohled"
                      },
                      {
                        "id": "b63b6226-0978-4155-8249-1ca396f6c7e7",
                        "source": "Telefon"
                      }
                ]
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /tunnels/{tunnelId}/reports/states

+ Parameters
    + tunnelId (required, string, `e27164e8-f8cd-47df-a5af-1c121e9aa94a`) ... String `tunnelId`which can identify tunnel.

### GET
**List of report states**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

    + Attributes (ReportState)
    
    + Header

             X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    

            {
                "states": [
                      {
                        "id": "e27164e8-f8cd-47df-a5af-1c121e9aa94a",
                        "state": "NEW"
                      },
                      {
                        "id": "b63b6226-0978-4155-8249-1ca396f6c7e7",
                        "state": "DONE"
                      }
                ]
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

# Group Contact
The contact resources can be used for managing contacts.

## /contacts

### GET
**List of contacts.**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200 (application/json)

    + Attributes (Contact)
    
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
    
    + Body 
    
            {
                "contacts": [
                    {
                        "organization": "PČR",
                        "workplace": "Oddělení dopravy",
                        "position": "plk.",
                        "forename": "Ondřej",
                        "surname": "Schrabal",
                        "phone": "987654321",
                        "mobile": "123456789",
                        "email": "hrabalo@quanti.cz",
                        "analogRdst": "110Mhz",
                        "pegas": ""
                    },
                    {
                        "organization": "PČR",
                        "workplace": "Oddělení vražd",
                        "position": "col.",
                        "forename": "Vlastislav",
                        "surname": "Blažek",
                        "phone": "987654321",
                        "mobile": "123456789",
                        "email": "blazekv@quanti.cz",
                        "analogRdst": "110Mhz",
                        "pegas": "10Mhz"
                    }
                ]
            }
        
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### POST
**Creates contact**

+ Request
    + Attributes (Contact)
    
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>
    
    + Body 
    
            {
                "organization": "PČR",
                "workplace": "Oddělení dopravy",
                "position": "plk.",
                "forename": "Ondřej",
                "surname": "Schrabal",
                "phone": "987654321",
                "mobile": "123456789",
                "email": "hrabalo@quanti.cz",
                "analogRdst": "110Mhz",
                "pegas": ""
            }
            
+ Response 201 (application/json)
    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
            Location: /contacts/{id}
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

## /contacts/{id}

+ Parameters
    + id (required, string, `b63b6226-0978-4155-8249-1ca396f6c7e7`) ... String `id`which can identify contact.

### GET
**Get contact**

+ Request
    + Attributes (Contact)

    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 200

    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
            
            
    + Body
    
            {
                "organization": "PČR",
                "workplace": "Oddělení dopravy",
                "position": "plk.",
                "forename": "Ondřej",
                "surname": "Schrabal",
                "phone": "987654321",
                "mobile": "123456789",
                "email": "hrabalo@quanti.cz",
                "analogRdst": "110Mhz",
                "pegas": ""
            }

+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### PUT
**Update contact**

+ Request
    + Attributes (Contact)

    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

    + Body
    
            {
                "organization": "PČR",
                "workplace": "Oddělení dopravy",
                "position": "plk.",
                "forename": "Ondřej",
                "surname": "Schrabal",
                "phone": "987654321",
                "mobile": "123456789",
                "email": "hrabalo@quanti.cz",
                "analogRdst": "110Mhz",
                "pegas": ""
            }

+ Response 204

    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00

+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503

### DELETE
**Deletes contact**

+ Request
    + Header
    
            Content-Type: application/json
            X-Api-Key: <your-private-token-key>

+ Response 204

    + Header
    
            X-Time: 2014-09-11T17:02:27.761+02:00
            
+ Response 401
+ Response 403
+ Response 404
+ Response 405
+ Response 406
+ Response 500
+ Response 503